apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: poc-dev
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: fluxint
    namespace: flux-system
  path: ./clusters/poc-dev
  prune: true
  wait: true
  timeout: 2m
  dependsOn:
  - name: flux-system
