apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/flux-system
  sourceRef:
    kind: GitRepository
    name: fluxint
    namespace: flux-system
  prune: true
  resources:
  - kustomization-poc-dev.yaml
  - kustomization-poc-uat.yaml
  dependsOn: []
