apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/flux-system
  sourceRef:
    kind: GitRepository
    name: fluxint
    namespace: flux-system
  resources:
  - kustomization-poc-dev.yaml
  - kustomization-poc-uat.yaml
