apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: poc-uat
  namespace: poc-uat
spec:
  interval: 5m
  path: ./clusters/poc-uat
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxint
    namespace: flux-system
