apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: poc-dev
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/poc-dev
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  validation: client
  timeout: 2m
