apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: poc-dev
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/poc-dev
  sourceRef:
    kind: GitRepository
    name: fluxint
    namespace: flux-system
